# Generated by Django 5.0.1 on 2024-01-27 05:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_bc_remove_customuser_address_remove_customuser_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.CharField(max_length=300)),
                ('family_member_count', models.PositiveIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='admin_profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='BC',
        ),
        migrations.RemoveField(
            model_name='student_profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacher_profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Admin_Profile',
        ),
        migrations.DeleteModel(
            name='Student_Profile',
        ),
        migrations.DeleteModel(
            name='Teacher_Profile',
        ),
    ]
